[package]
name = "tftp"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.26", features = ["derive", "color"] }
anstyle = "1.0.10"
tokio = { version = "1", features = ["full"] }